
# At development time, it is convenient to mount the local folder as a volume,
# so that local changes to the notebooks and (more importantly) to the modules
# are reflected in the container, and vice-versa. At deployment time, the
# "volumes" section in this file can be commented

version: '2.0'
services:
  jupyter:
    build: .
    ports:
    - "8888:8888"
    volumes:
    - .:/app



